title:             Tokiota Blog
email:             tokiota@tokiota.com
description:       Un blog de Tokiota
author:            Tokiota
baseurl:           ""
url:               "http://tokiota.github.io"

# Social Profiles
twitter_username:  Tokiota_IT
github_username:   Tokiota
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
