# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       tokiota/tokiota.github.io

exclude: [vendor]

# Setup
name:             "Tokiota"
url:              https://tokiota.com
twitter:          Tokiota_IT
facebook:         https://es-es.facebook.com/tokiota.es
youtube:          https://www.youtube.com/channel/UCfiDuxp9zGMJ7NIFyjRuHWQ
instagram:        https://www.instagram.com/tokiota_it
profile_github:   https://github.com/tokiota
profile_linkedin: https://www.linkedin.com/company/tokiota/

paginate:         10

title:            "Blog de Tokiotas"
tagline:          "pasión por la tecnología"
description:      "El viaje más largo comienza con un primer paso."
locale:           es_es
encoding:         utf-8
url:              https://tokiota.github.io
baseurl:          https://tokiota.github.io/
google_analytics: UA-XXXXXXXXX-X
icon:             /public/img/defaulticon.jpg

plugins: 
  - jekyll-sitemap
  - jemoji